/**
 * JWT issue/verify using Ed25519 (jose lib).
 * Server signing key loaded from JWT_SIGNING_KEY env (Ed25519 private hex).
 * In dev, key is auto-generated by ensureDevKeys() on first boot.
 */

import { SignJWT, jwtVerify, importPKCS8, importJWK, exportSPKI } from 'jose';
import * as ed from '@noble/ed25519';
import { sha512 } from '@noble/hashes/sha512';

ed.etc.sha512Sync = (...m) => sha512(ed.etc.concatBytes(...m));

let cachedPrivateKey: CryptoKey | null = null;
let cachedPublicKey: CryptoKey | null = null;
let cachedPubSpki: string | null = null;

async function getKeys() {
  if (cachedPrivateKey && cachedPublicKey) {
    return { priv: cachedPrivateKey, pub: cachedPublicKey };
  }
  const hex = process.env.JWT_SIGNING_KEY;
  if (!hex) throw new Error('JWT_SIGNING_KEY not set');

  const privBytes = Buffer.from(hex, 'hex');
  const pubBytes = await ed.getPublicKey(privBytes);

  // Build JWK from raw bytes
  const privJwk = {
    kty: 'OKP',
    crv: 'Ed25519',
    d: Buffer.from(privBytes).toString('base64url'),
    x: Buffer.from(pubBytes).toString('base64url'),
  };
  const pubJwk = {
    kty: 'OKP',
    crv: 'Ed25519',
    x: Buffer.from(pubBytes).toString('base64url'),
  };

  cachedPrivateKey = (await importJWK(privJwk, 'EdDSA')) as CryptoKey;
  cachedPublicKey = (await importJWK(pubJwk, 'EdDSA')) as CryptoKey;
  return { priv: cachedPrivateKey, pub: cachedPublicKey };
}

export interface SessionClaims {
  sub: string;     // user_id
  sid: string;     // session_id (jti)
  email: string;
  role: 'OWNER' | 'SUPERVISOR' | 'WORKER' | 'OBSERVER';
}

export async function issueSessionJwt(claims: SessionClaims, ttlSec: number, issuer: string, audience: string): Promise<string> {
  const { priv } = await getKeys();
  return new SignJWT({ email: claims.email, role: claims.role })
    .setProtectedHeader({ alg: 'EdDSA', typ: 'JWT' })
    .setSubject(claims.sub)
    .setJti(claims.sid)
    .setIssuedAt()
    .setExpirationTime(`${ttlSec}s`)
    .setIssuer(issuer)
    .setAudience(audience)
    .sign(priv);
}

export async function verifySessionJwt(token: string, issuer: string, audience: string): Promise<SessionClaims> {
  const { pub } = await getKeys();
  const { payload } = await jwtVerify(token, pub, { issuer, audience });
  if (typeof payload.sub !== 'string') throw new Error('jwt: missing sub');
  if (typeof payload.jti !== 'string') throw new Error('jwt: missing jti');
  if (typeof payload.email !== 'string') throw new Error('jwt: missing email');
  if (typeof payload.role !== 'string') throw new Error('jwt: missing role');
  return {
    sub: payload.sub,
    sid: payload.jti,
    email: payload.email,
    role: payload.role as SessionClaims['role'],
  };
}
