#!/usr/bin/env bash
# One-time founder setup for running the admin portal LOCALLY (macOS / Linux / Git Bash on Windows)
# + exposing it via Cloudflare Tunnel at https://admin.unityailab.com.
#
# Mirrors setup-cloudflare-tunnel-local.ps1. Run once.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TUNNEL_NAME="${TUNNEL_NAME:-admin-portal-local}"
ADMIN_HOST="${ADMIN_HOST:-admin.unityailab.com}"

echo
echo "==> Unity AI Lab admin portal — local Cloudflare Tunnel setup"
echo "    Repo root: $REPO_ROOT"
echo "    Tunnel:    $TUNNEL_NAME"
echo "    Hostname:  $ADMIN_HOST"
echo

# ============================================================================
# 1. Install cloudflared
# ============================================================================
if ! command -v cloudflared >/dev/null 2>&1; then
    echo "==> Installing cloudflared..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        if command -v brew >/dev/null 2>&1; then
            brew install cloudflared
        else
            echo "    Install Homebrew first, then: brew install cloudflared"
            exit 1
        fi
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb" -o /tmp/cloudflared.deb
        sudo dpkg -i /tmp/cloudflared.deb
    else
        echo "    Unsupported OS. Install cloudflared manually: https://developers.cloudflare.com/cloudflared/install"
        exit 1
    fi
fi
echo "    ✓ cloudflared: $(which cloudflared)"

# ============================================================================
# 2. Cloudflare login
# ============================================================================
CERT_PATH="$HOME/.cloudflared/cert.pem"
if [ ! -f "$CERT_PATH" ]; then
    echo
    echo "==> Cloudflare browser login (opens a one-time URL)"
    echo "    Pick the unityailab.com zone."
    cloudflared tunnel login
else
    echo "    ✓ Cloudflare cert already present"
fi

# ============================================================================
# 3. Create tunnel (idempotent)
# ============================================================================
echo
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
    echo "==> Tunnel '$TUNNEL_NAME' already exists"
else
    echo "==> Creating tunnel '$TUNNEL_NAME'"
    cloudflared tunnel create "$TUNNEL_NAME"
fi

# ============================================================================
# 4. Route DNS
# ============================================================================
echo
echo "==> Routing DNS $ADMIN_HOST -> tunnel..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$ADMIN_HOST" || echo "    (DNS may already be routed)"

# ============================================================================
# 5. Write tunnel config
# ============================================================================
TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v name="$TUNNEL_NAME" '$2 == name { print $1 }')
if [ -z "$TUNNEL_ID" ]; then
    echo "    !! Could not find tunnel UUID. Check 'cloudflared tunnel list'."
    exit 1
fi
CFG_DIR="$HOME/.cloudflared"
CFG_FILE="$CFG_DIR/config.yml"
mkdir -p "$CFG_DIR"
cat > "$CFG_FILE" <<EOF
# Auto-generated by scripts/setup-cloudflare-tunnel-local.sh
tunnel: $TUNNEL_ID
credentials-file: $CFG_DIR/$TUNNEL_ID.json

ingress:
  - hostname: $ADMIN_HOST
    service: http://localhost:3000
  - service: http_status:404
EOF
echo "    ✓ tunnel config: $CFG_FILE"

# ============================================================================
# 6. Generate secrets + write server/.env
# ============================================================================
cd "$REPO_ROOT"
echo
echo "==> Generating signing secrets..."
JWT_KEY=$(node -e "
  import('@noble/ed25519').then(async(ed)=>{
    const {sha512} = await import('@noble/hashes/sha512');
    ed.etc.sha512Sync = (...m)=>sha512(ed.etc.concatBytes(...m));
    process.stdout.write(Buffer.from(ed.utils.randomPrivateKey()).toString('hex'));
  });
")
CSRF_KEY=$(node -e "process.stdout.write(require('crypto').randomBytes(48).toString('base64url'));")
WEBHOOK_KEY=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('base64url'));")

cat > server/.env <<EOF
# Generated by setup-cloudflare-tunnel-local.sh
# LOCAL TUNNEL MODE — backend on this PC, exposed via Cloudflare at https://$ADMIN_HOST
NODE_ENV=development
PORT=3000
HOST=127.0.0.1
PUBLIC_BASE_URL=https://$ADMIN_HOST

DATABASE_URL=sqlite://./server/data/dev.db

DEV_AUTH_BYPASS=true
ADMIN_CLAIM_OPEN=false

JWT_SIGNING_KEY=$JWT_KEY
JWT_ISSUER=$ADMIN_HOST
JWT_AUDIENCE=$ADMIN_HOST
JWT_TTL_SECONDS=43200

CSRF_COOKIE_SECRET=$CSRF_KEY

WEBAUTHN_RP_ID=$ADMIN_HOST
WEBAUTHN_RP_NAME=Unity AI Lab Admin Portal
WEBAUTHN_ORIGIN=https://$ADMIN_HOST

FILE_STORAGE_KIND=local
FILE_STORAGE_LOCAL_PATH=./server/data/uploads

GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_INSTALLATION_ID=
GITHUB_WEBHOOK_HMAC_SECRET=$WEBHOOK_KEY

LOG_LEVEL=info
LOG_PRETTY=true

RATELIMIT_LOGIN_PER_15MIN=5
RATELIMIT_API_PER_MIN=600
RATELIMIT_WS_MSG_PER_SEC=10
EOF
chmod 600 server/.env
echo "    ✓ server/.env written + chmod 600"

echo
echo "===================================================================="
echo "✓ Local Cloudflare Tunnel setup complete."
echo "===================================================================="
echo
echo "  Tunnel:           $TUNNEL_NAME ($TUNNEL_ID)"
echo "  Public hostname:  https://$ADMIN_HOST"
echo "  Backend port:     localhost:3000"
echo
echo "DAILY USE — start backend + tunnel together:"
echo "  ./start-tunnel.sh    (opens 2 terminal windows on macOS, foreground on Linux)"
echo
echo "OR separately in 2 terminals:"
echo "  Terminal 1: npm run dev"
echo "  Terminal 2: cloudflared tunnel run $TUNNEL_NAME"
echo
echo "FIRST CLAIM (founder bootstrap):"
echo "  1. Start the stack (above)"
echo "  2. Open https://$ADMIN_HOST/admin/ in your browser"
echo "  3. Dev tab → pick yourself → land on dashboard → set password from sidebar"
echo "     (OR run .claude/start.bat / start.sh → setup wizard Phase 8.5)"
echo
echo "BEFORE DISTRIBUTING .claude/ TO OTHER ADMINS:"
echo "  1. Edit server/.env: set DEV_AUTH_BYPASS=false (kills public dev picker)"
echo "  2. Restart npm run dev"
echo "  3. From dashboard right sidebar: 'Open Claim Window'"
echo "  4. Zip + send .claude/ folder to other admins (Signal/USB)"
echo "  5. Each runs their .claude/start → claims their account"
echo "  6. Close claim window after all 4 enrolled"
echo
echo "NOTE: while your PC is OFF, https://$ADMIN_HOST is unreachable."
echo "      For always-on, run scripts/setup-cloudflare-vps.sh on a \$5 Hetzner instead."
echo
