#Requires -RunAsAdministrator
<#
.SYNOPSIS
  One-time founder setup for running the admin portal LOCALLY on this PC + exposing it
  via Cloudflare Tunnel at https://admin.unityailab.com.

.DESCRIPTION
  Installs cloudflared, logs in to Cloudflare (one-time browser auth), creates a tunnel
  named 'admin-portal-local', routes DNS admin.unityailab.com → that tunnel, generates
  signing secrets, writes server\.env, and prints how to start the backend + tunnel.

  Run once. After that, daily use is `start-tunnel.bat`.

.NOTES
  Run as Administrator (winget needs it).
  Requires Node 20+ already installed.
#>

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$TunnelName = 'admin-portal-local'
$AdminHost = 'admin.unityailab.com'

Write-Host ""
Write-Host "==> Unity AI Lab admin portal — local Cloudflare Tunnel setup" -ForegroundColor Cyan
Write-Host "    Repo root: $RepoRoot"
Write-Host "    Tunnel:    $TunnelName"
Write-Host "    Hostname:  $AdminHost"
Write-Host ""

# ============================================================================
# 1. Install cloudflared
# ============================================================================
Write-Host "==> Checking for cloudflared..." -ForegroundColor Yellow
$cloudflared = Get-Command cloudflared -ErrorAction SilentlyContinue
if (-not $cloudflared) {
    Write-Host "    Not found. Installing via winget..."
    winget install --id Cloudflare.cloudflared -e --silent --accept-package-agreements --accept-source-agreements
    # Refresh PATH for current session
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User')
    $cloudflared = Get-Command cloudflared -ErrorAction SilentlyContinue
    if (-not $cloudflared) {
        Write-Host "    !! cloudflared still not on PATH. Open a new PowerShell window and re-run." -ForegroundColor Red
        exit 1
    }
}
Write-Host "    ✓ cloudflared found at $($cloudflared.Path)"

# ============================================================================
# 2. Cloudflare login (one-time)
# ============================================================================
$origCertPath = Join-Path $env:USERPROFILE '.cloudflared\cert.pem'
if (-not (Test-Path $origCertPath)) {
    Write-Host ""
    Write-Host "==> Cloudflare browser login (opens a one-time URL)" -ForegroundColor Yellow
    Write-Host "    Pick the unityailab.com zone when prompted."
    cloudflared tunnel login
} else {
    Write-Host "    ✓ Cloudflare cert already present at $origCertPath"
}

# ============================================================================
# 3. Create tunnel (idempotent)
# ============================================================================
Write-Host ""
Write-Host "==> Creating tunnel '$TunnelName' (skips if exists)..." -ForegroundColor Yellow
$existing = cloudflared tunnel list 2>$null | Out-String
if ($existing -match $TunnelName) {
    Write-Host "    ✓ Tunnel '$TunnelName' already exists"
} else {
    cloudflared tunnel create $TunnelName
    Write-Host "    ✓ Tunnel created"
}

# ============================================================================
# 4. Route DNS
# ============================================================================
Write-Host ""
Write-Host "==> Routing DNS $AdminHost -> tunnel..." -ForegroundColor Yellow
try {
    cloudflared tunnel route dns $TunnelName $AdminHost
    Write-Host "    ✓ DNS record created/updated"
} catch {
    Write-Host "    (DNS may already be routed — continuing) $_"
}

# ============================================================================
# 5. Write tunnel config
# ============================================================================
$cfgDir = Join-Path $env:USERPROFILE '.cloudflared'
$cfgFile = Join-Path $cfgDir 'config.yml'
# Find the tunnel UUID
$tunList = cloudflared tunnel list 2>$null | Out-String
$tunnelLine = ($tunList -split "`n") | Where-Object { $_ -match $TunnelName } | Select-Object -First 1
$tunnelId = ($tunnelLine -split '\s+')[0].Trim()
if (-not $tunnelId) {
    Write-Host "    !! Could not determine tunnel UUID — check 'cloudflared tunnel list' manually" -ForegroundColor Red
    exit 1
}
$credsFile = Join-Path $cfgDir "$tunnelId.json"

Write-Host ""
Write-Host "==> Writing $cfgFile..." -ForegroundColor Yellow
@"
# Auto-generated by scripts/setup-cloudflare-tunnel-local.ps1
tunnel: $tunnelId
credentials-file: $credsFile

ingress:
  - hostname: $AdminHost
    service: http://localhost:3000
  - service: http_status:404
"@ | Set-Content -Path $cfgFile -Encoding utf8

Write-Host "    ✓ Tunnel config written"

# ============================================================================
# 6. Generate server secrets + write server\.env
# ============================================================================
Write-Host ""
Write-Host "==> Generating signing secrets..." -ForegroundColor Yellow
Push-Location $RepoRoot
$jwtKey = node -e "
  import('@noble/ed25519').then(async(ed)=>{
    const {sha512} = await import('@noble/hashes/sha512');
    ed.etc.sha512Sync = (...m)=>sha512(ed.etc.concatBytes(...m));
    process.stdout.write(Buffer.from(ed.utils.randomPrivateKey()).toString('hex'));
  });
"
$csrfKey = node -e "process.stdout.write(require('crypto').randomBytes(48).toString('base64url'));"
$webhookKey = node -e "process.stdout.write(require('crypto').randomBytes(32).toString('base64url'));"

$envFile = Join-Path $RepoRoot 'server\.env'
Write-Host "==> Writing $envFile..." -ForegroundColor Yellow
@"
# Generated by setup-cloudflare-tunnel-local.ps1
# LOCAL TUNNEL MODE — backend runs on this PC, exposed via Cloudflare at https://$AdminHost
NODE_ENV=development
PORT=3000
HOST=127.0.0.1
PUBLIC_BASE_URL=https://$AdminHost

DATABASE_URL=sqlite://./server/data/dev.db

# Dev bypass stays ON because this IS the founder's dev box — but the tunnel exposes it
# publicly, so the dev login picker is reachable from the internet. Disable BEFORE distributing
# the .claude/ template to other admins (set to false + restart).
DEV_AUTH_BYPASS=true

# Open this when distributing universal .claude/ to the other 3 admins, then close after.
ADMIN_CLAIM_OPEN=false

JWT_SIGNING_KEY=$jwtKey
JWT_ISSUER=$AdminHost
JWT_AUDIENCE=$AdminHost
JWT_TTL_SECONDS=43200

CSRF_COOKIE_SECRET=$csrfKey

WEBAUTHN_RP_ID=$AdminHost
WEBAUTHN_RP_NAME=Unity AI Lab Admin Portal
WEBAUTHN_ORIGIN=https://$AdminHost

FILE_STORAGE_KIND=local
FILE_STORAGE_LOCAL_PATH=./server/data/uploads

GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_APP_INSTALLATION_ID=
GITHUB_WEBHOOK_HMAC_SECRET=$webhookKey

LOG_LEVEL=info
LOG_PRETTY=true

RATELIMIT_LOGIN_PER_15MIN=5
RATELIMIT_API_PER_MIN=600
RATELIMIT_WS_MSG_PER_SEC=10
"@ | Set-Content -Path $envFile -Encoding utf8

# Lock down the env file (best-effort on Windows)
icacls $envFile /inheritance:r /grant:r "$($env:USERNAME):F" | Out-Null
Pop-Location

Write-Host "    ✓ server\.env written + locked"

# ============================================================================
# Done — print next steps
# ============================================================================
Write-Host ""
Write-Host "====================================================================" -ForegroundColor Green
Write-Host "✓ Local Cloudflare Tunnel setup complete." -ForegroundColor Green
Write-Host "====================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Tunnel:           $TunnelName ($tunnelId)"
Write-Host "  Public hostname:  https://$AdminHost"
Write-Host "  Backend port:     localhost:3000"
Write-Host ""
Write-Host "DAILY USE — start backend + tunnel together:" -ForegroundColor Yellow
Write-Host "  start-tunnel.bat     (opens 2 terminal windows)"
Write-Host ""
Write-Host "OR start them separately in 2 terminals:" -ForegroundColor Yellow
Write-Host "  Terminal 1: npm run dev"
Write-Host "  Terminal 2: cloudflared tunnel run $TunnelName"
Write-Host ""
Write-Host "FIRST CLAIM (founder bootstrap):" -ForegroundColor Yellow
Write-Host "  1. Start the stack (above)"
Write-Host "  2. Open https://$AdminHost/admin/ in your browser"
Write-Host "  3. Use the Dev tab → pick yourself → set password from the dashboard"
Write-Host "     (OR run .claude/start.bat → setup wizard Phase 8.5)"
Write-Host ""
Write-Host "BEFORE DISTRIBUTING .claude/ TO OTHER ADMINS:" -ForegroundColor Yellow
Write-Host "  1. Set DEV_AUTH_BYPASS=false in server\.env (kills the dev login picker)"
Write-Host "  2. Restart npm run dev"
Write-Host "  3. From dashboard, open the claim window"
Write-Host "  4. Zip up the .claude/ folder and send to the other admins (Signal/USB)"
Write-Host "  5. Each runs THEIR .claude/start.bat → claims their account"
Write-Host "  6. Close the claim window after all 4 enrolled"
Write-Host ""
Write-Host "NOTE: while your PC is OFF, https://$AdminHost is unreachable. To always-on,"
Write-Host "      use scripts/setup-cloudflare-vps.sh on a $5 Hetzner box instead."
Write-Host ""
